export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export type REQUEST_PRODUCTS = typeof REQUEST_PRODUCTS

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export type RECEIVE_PRODUCTS = typeof RECEIVE_PRODUCTS

export const RECEIVE_ACTIVITYS = 'RECEIVE_ACTIVITYS'
export type RECEIVE_ACTIVITYS = typeof RECEIVE_ACTIVITYS 

export const RECEIVE_ADS = 'RECEIVE_ADS'
export type RECEIVE_ADS = typeof RECEIVE_ADS