export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export type REQUEST_PRODUCTS = typeof REQUEST_PRODUCTS

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export type RECEIVE_PRODUCTS = typeof RECEIVE_PRODUCTS