export const REQUEST_RODUCTS = 'REQUEST_RODUCTS'
export type REQUEST_RODUCTS = typeof REQUEST_RODUCTS

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export type RECEIVE_PRODUCTS = typeof RECEIVE_PRODUCTS