export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export type REQUEST_PRODUCTS = typeof REQUEST_PRODUCTS

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export type RECEIVE_PRODUCTS = typeof RECEIVE_PRODUCTS

export const RECEIVE_ACTIVITYS = 'RECEIVE_ACTIVITYS'
export type RECEIVE_ACTIVITYS = typeof RECEIVE_ACTIVITYS 

export const RECEIVE_ADS = 'RECEIVE_ADS'
export type RECEIVE_ADS = typeof RECEIVE_ADS

export const RECEIVE_PRODUCT_CATES = 'RECEIVE_PRODUCT_CATES'
export type RECEIVE_PRODUCT_CATES = typeof RECEIVE_PRODUCT_CATES

export const RECEIVE_PRODUCTLIST_BANNERS = 'RECEIVE_PRODUCTLIST_BANNERS'
export type RECEIVE_PRODUCTLIST_BANNERS = typeof RECEIVE_PRODUCTLIST_BANNERS

export const LOGIN = 'LOGIN'
export type LOGIN = typeof LOGIN

export const LOGOUT = 'LOGOUT'
export type LOGOUT = typeof LOGOUT 

export const SAVE_USER = 'SAVE_USER'
export type SAVE_USER = typeof SAVE_USER

export const CLEAR_USER = 'CLEAR_USER'
export type CLEAR_USER = typeof CLEAR_USER 

export const CHECK_LOGIN = 'CHECK_LOGIN'
export type CHECK_LOGIN = typeof CHECK_LOGIN

export const SET_TITLE = 'SET_TITLT'
export type SET_TITLE = typeof SET_TITLE

export const SET_SYSTEM = 'SET_SYSTEM'
export type SET_SYSTEM = typeof SET_SYSTEM 

export const SAVE_ORDER = 'SAVE_ORDER'
export type SAVE_ORDER = typeof SAVE_ORDER 

export const REQUEST_ORDER = 'REQUEST_ORDER'
export type REQUEST_ORDER = typeof REQUEST_ORDER

export const SET_CART_STATUS = 'SET_CART_STATUS'
export type SET_CART_STATUS = typeof SET_CART_STATUS

export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS'
export type SET_CART_PRODUCTS = typeof SET_CART_PRODUCTS 



